# Site settings
author: norioc
title: flatiron blog
header-img: img/home-bg.png
email: norionorioc@gmail.com
copyright_name: norioc
description: > # this means to ignore newlines until "baseurl:"
  journey at flatiron school
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  norioc

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
